### PR TITLE
move content that was built from checkstyle-8.8 tag into 8.8/ sub-folder

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@romani @daniilyar in order to be able to keep several version of the CS doc site on http://checkstyle.org, I suggest to use per-version sub-directories instead of having the content at root. 

This PR 2nd commit also proposes a minimalistic root index.html with a redirect header to current version.

**Comment by rnveach** [comment]
do we really need a versioned directory?
Oracle does it for their javadocs and whenever you search on a class in google, it usually always returns the oldest version (Java 6 for example). Then to look at the latest, you need to find the current release version and swap out the old number for the new in the URL. This usually works as long as the directory/file names didn't change any.

**Comment by romani** [comment]
I am not ok, all links to latest doc should be as non redirected.

I think it is good to have several old web sites, so they should be checkstyle/X.X/..... probably but how we will tell google index robots to make main pages to be top ranked.

@vorburger , it is better to make issue and discuss and got approval for your steps before implementation. There are bunch of us here we need to come to same resolution on such big questions.

**Comment by vorburger** [comment]
> see comment above

@romani @rnveach I'm trying to understand if I should Abandon this or what specific changes to this PR you are requesting to merge it... 

> I am not ok, all links to latest doc should be as non redirected.

so remove the 2nd commit which adds root index.html with redirect to version

> how we will tell google index robots to make main pages to be top ranked

I doubt you really can. However one idea could be have a /latest/ ln -s symlink. I've tested this on another Git Hub pages (personal home page) and apparently this seems to work. Would you like this PR to be amended with that? And have a redirect to that /latest/ in the root index.html instead of to 8.8/ ?

> better to make issue and discuss and got approval for your steps before implementation

No no, this is open source, we work together, it's not someone "approving" something of someone else...  It's actually great to propose something concrete and then discuss feedback against it in comments of a PR... :smiley:

**Comment by romani** [comment]
> No no, this is open source, we work together, it's not someone "approving" something of someone else..

Tell me a bout this :) .
Open source has more rules than even proprietary code. Nothing is done on desire of one individual. Even between maintainers were are disagreements, but in cases we result in constructive discussion and agreements. "we  work together" .... so please open the issue and lets got approval from all/most participants.

> so remove the 2nd commit which adds root index.html with redirect to version

Right now, I do not like sub folders. We even did not migrate to new location as-is and you discuss next stage problem to let users see previous versions documentation.
I appreciate your desire to help, but lets do all steps by step.

**Comment by vorburger** [comment]
OK no problem - closing to abandon this.

**Pull request closed without merging**
